### ISSUE TITLE
Theme does not appear to have a configuration file.

### ISSUE THREAD

**Issue by lramage94** [lramage94/mkdocs-bootstrap386#1]
```
WARNING -  The theme 'bootstra-386' does not appear to have a configuration file. Please upgrade to a current version of the theme.
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: /home/ubuntu/seven-sun-downs/site
ERROR   -  Error building page index.md
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mkdocs/__main__.py", line 156, in build_command
    ), dirty=not clean)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 282, in build
    build_pages(config, dirty=dirty)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 242, in build_pages
    _build_page(page, config, site_navigation, env)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/mkdocs/commands/build.py", line 150, in _build_page
    template = env.get_template('main.html')
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: main.html
```

**Comment by lramage94** [comment]
https://github.com/mkdocs/mkdocs-bootstrap/issues/17
